name: Integration CI

on:
  push:
    branches: ["feature/Product-Seller", "main"]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker compose config
      - run: docker compose build
